name: CI pipeline for push and pull on main branch

on:
  push:
    branches: [ main ]
  
  pull:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node version 12.x
      - uses: actions/setup-node@v1

        with:
          node-version: '14.x'

      - name: Installing and caching dependencies
        run: npm ci

      - name: Building package
        run: npm run build --if-present

      - name: Testing the package
        run: npm run test
